### ISSUE TITLE
Is this still works? Is Google still using AnyMote protocols?

### ISSUE THREAD

**Issue by osfunapps** [stevenle/googletv-anymote#3]
I was just wondering if this is still relevant

**Comment by r3a1d3a1** [comment]
Based on [SO](https://stackoverflow.com/questions/46262046/what-protocol-does-android-tv-remote-use), most likely not.

**Comment by stevenle** [comment]
anymote is a deprecated protocol. i'll update the repo so people are aware.

**Comment by Aymkdn** [comment]
What is the new protocol then? It's been complicated to find any info about it…

Thanks
